const oneMonthPackage = [
  {
    ability: "تعداد مکالمه هوشمند",
    free: "100",
    economic: "500",
    professional: "1000 + 150 هدیه",
  },
  {
    ability: "حجم فایل ارسالی",
    free: "2 مگابایت",
    economic: "5 مگابایت",
    professional: "8 مگابایت",
  },
  {
    ability: "تعداد اپراتور",
    free: "2",
    economic: "4",
    professional: "8",
  },
  {
    ability: "گزارشات عملکرد ربات ",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "شخصی سازی ویجت",
    free: false,
    economic: true,
    professional: true,
  },
  { ability: "دسترسی API", free: false, economic: false, professional: false },
  {
    ability: "قابلیت اتصال به تلگرام",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "پیام های آماده ",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "فرم دریافت اطلاعات از کاربر",
    free: false,
    economic: false,
    professional: true,
  },
  {
    ability: "نمایش محصولات * (ویترین ساز)",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "امکان حذف متن تبلیغ هیکس",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "مسدودسازی کاربران مزاحم",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "ضبط و ارسال صدا",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "خروجی اکسل از گزارشات و اطلاعات",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "نگهداری تاریخچه مکالمات",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "امکان تغییر پکیج کاربری(کمتر از 48 ساعت)",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "قابلیت اتصال به واتساپ",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "کنترل کیفیت و رضایت مندی",
    free: false,
    economic: false,
    professional: true,
  },
  {
    ability: "اطلاعات بازدید کنندگان حین گفتگو",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "امکان پاسخ گویی مکالمات در 24 ساعت شبانه روز(حتی روزهای تعطیل)",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "اپلیکیشن تحت وب",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "گفتوگو همزمان با کاربران",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: " شخصی سازی لوگو ویجت",
    free: false,
    economic: false,
    professional: true,
  },
  {
    ability: "مانیتورینگ لحظه ای بازدیدکنندگان",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "پاسخ آماده با امکان شخصی سازی",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "وبینار رایگان آموزشی به همراه فایل های آماده",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "امکان دانلود فاکتور رسمی",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "کمک به سئو وبسایت *",
    free: false,
    economic: true,
    professional: true,
  },
  { ability: " وب هوک", free: false, economic: false, professional: false },
  {
    ability: "نمایش دسته بندی های سایت",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "مقایسه 2 محصول انتخابی کاربران ",
    free: false,
    economic: false,
    professional: false,
  },
  {
    ability: "امکان ارسال خودکار کد تخفیف",
    free: false,
    economic: false,
    professional: true,
  },
  {
    ability: "تعامل هوشمند با کاربران",
    free: false,
    economic: true,
    professional: true,
  },
  {
    ability: "مشاوره به کاربران با توجه به اطلاعات وبسایت",
    free: false,
    economic: true,
    professional: true,
  },
];

const sixMonthPackage = [
  { ability: "تعداد مکالمه هوشمند", economic: "3800", professional: "7600" },
  {
    ability: "حجم فایل ارسالی",
    economic: "2 مگابایت",
    professional: "5 مگابایت",
  },
  { ability: "تعداد اپراتور", economic: "8", professional: "10" },
  { ability: "گزارشات عملکرد ربات ", economic: false, professional: true },
  { ability: "شخصی سازی ویجت", economic: true, professional: true },
  { ability: "دسترسی API", economic: false, professional: true },
  { ability: "قابلیت اتصال به تلگرام", economic: false, professional: false },
  { ability: "پیام های آماده ", economic: true, professional: true },
  {
    ability: "فرم دریافت اطلاعات از کاربر",
    economic: true,
    professional: true,
  },
  {
    ability: "نمایش محصولات * (ویترین ساز)",
    economic: true,
    professional: true,
  },
  { ability: "امکان حذف متن تبلیغ هیکس", economic: false, professional: false },
  { ability: "مسدودسازی کاربران مزاحم", economic: true, professional: true },
  { ability: "ضبط و ارسال صدا", economic: true, professional: true },
  {
    ability: "خروجی اکسل از گزارشات و اطلاعات",
    economic: false,
    professional: true,
  },
  { ability: "نگهداری تاریخچه مکالمات", economic: false, professional: false },
  {
    ability: "امکان تغییر پکیج کاربری(کمتر از 48 ساعت)",
    economic: true,
    professional: true,
  },
  { ability: "قابلیت اتصال به واتساپ", economic: false, professional: false },
  { ability: "کنترل کیفیت و رضایت مندی", economic: false, professional: true },
  {
    ability: "اطلاعات بازدید کنندگان حین گفتگو",
    economic: true,
    professional: true,
  },
  {
    ability: "امکان پاسخ گویی مکالمات در 24 ساعت شبانه روز(حتی روزهای تعطیل)",
    economic: false,
    professional: false,
  },
  { ability: "اپلیکیشن تحت وب", economic: true, professional: true },
  { ability: "گفتوگو همزمان با کاربران", economic: true, professional: true },
  { ability: " شخصی سازی لوگو ویجت", economic: false, professional: true },
  {
    ability: "مانیتورینگ لحظه ای بازدیدکنندگان",
    economic: true,
    professional: true,
  },
  {
    ability: "پاسخ آماده با امکان شخصی سازی",
    economic: false,
    professional: false,
  },
  {
    ability: "وبینار رایگان آموزشی به همراه فایل های آماده",
    economic: true,
    professional: true,
  },
  { ability: "امکان دانلود فاکتور رسمی", economic: false, professional: false },
  { ability: "کمک به سئو وبسایت *", economic: true, professional: true },
  { ability: " وب هوک", economic: false, professional: false },
  { ability: "نمایش دسته بندی های سایت", economic: true, professional: true },
  {
    ability: "مقایسه 2 محصول انتخابی کاربران ",
    economic: false,
    professional: false,
  },
  {
    ability: "امکان ارسال خودکار کد تخفیف",
    economic: true,
    professional: true,
  },
  { ability: "تعامل هوشمند با کاربران", economic: true, professional: true },
  {
    ability: "مشاوره به کاربران با توجه به اطلاعات وبسایت",
    economic: true,
    professional: true,
  },
];

const oneYearPackage = [
  { ability: "تعداد مکالمه هوشمند", economic: "12000", professional: "23000" },
  {
    ability: "حجم فایل ارسالی",
    economic: "60 مگابایت",
    professional: "110 مگابایت",
  },
  { ability: "تعداد اپراتور", economic: "نامحدود", professional: "نامحدود" },
  { ability: "گزارشات عملکرد ربات ", economic: false, professional: true },
  { ability: "شخصی سازی ویجت", economic: true, professional: true },
  { ability: "دسترسی API", economic: false, professional: true },
  { ability: "قابلیت اتصال به تلگرام", economic: true, professional: true },
  { ability: "پیام های آماده ", economic: true, professional: true },
  {
    ability: "فرم دریافت اطلاعات از کاربر",
    economic: true,
    professional: true,
  },
  {
    ability: "نمایش محصولات * (ویترین ساز)",
    economic: true,
    professional: true,
  },
  { ability: "امکان حذف متن تبلیغ هیکس", economic: false, professional: true },
  { ability: "مسدودسازی کاربران مزاحم", economic: true, professional: true },
  { ability: "ضبط و ارسال صدا", economic: true, professional: true },
  {
    ability: "خروجی اکسل از گزارشات و اطلاعات",
    economic: false,
    professional: true,
  },
  { ability: "نگهداری تاریخچه مکالمات", economic: false, professional: false },
  {
    ability: "امکان تغییر پکیج کاربری(کمتر از 48 ساعت)",
    economic: true,
    professional: true,
  },
  { ability: "قابلیت اتصال به واتساپ", economic: false, professional: true },
  { ability: "کنترل کیفیت و رضایت مندی", economic: false, professional: true },
  {
    ability: "اطلاعات بازدید کنندگان حین گفتگو",
    economic: true,
    professional: true,
  },
  {
    ability: "امکان پاسخ گویی مکالمات در 24 ساعت شبانه روز(حتی روزهای تعطیل)",
    economic: false,
    professional: false,
  },
  { ability: "اپلیکیشن تحت وب", economic: true, professional: true },
  { ability: "گفتوگو همزمان با کاربران", economic: true, professional: true },
  { ability: " شخصی سازی لوگو ویجت", economic: false, professional: true },
  {
    ability: "مانیتورینگ لحظه ای بازدیدکنندگان",
    economic: true,
    professional: true,
  },
  {
    ability: "پاسخ آماده با امکان شخصی سازی",
    economic: false,
    professional: false,
  },
  {
    ability: "وبینار رایگان آموزشی به همراه فایل های آماده",
    economic: true,
    professional: true,
  },
  { ability: "امکان دانلود فاکتور رسمی", economic: true, professional: true },
  { ability: "کمک به سئو وبسایت *", economic: true, professional: true },
  { ability: " وب هوک", economic: false, professional: false },
  { ability: "نمایش دسته بندی های سایت", economic: true, professional: true },
  {
    ability: "مقایسه 2 محصول انتخابی کاربران ",
    economic: false,
    professional: true,
  },
  {
    ability: "امکان ارسال خودکار کد تخفیف",
    economic: true,
    professional: true,
  },
  { ability: "تعامل هوشمند با کاربران", economic: true, professional: true },
  {
    ability: "مشاوره به کاربران با توجه به اطلاعات وبسایت",
    economic: true,
    professional: true,
  },
];

export { oneMonthPackage, sixMonthPackage, oneYearPackage };
